version: '3.8'

services:
  cassandra:
    image: cassandra:4.0.17-jammy
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra      